### ISSUE TITLE
Add theme editing

### ISSUE THREAD

**Issue by toolatetotheparty** [metarmask/dom-distiller-reading-mode#1]
The dark theme is too hard on the eyes. Thanks.

**Comment by toolatetotheparty** [comment]
I'm bumping the request. Your app is the fastest when switching to reading mode, but the contrast of the dark theme is too jarring for me. Only two color settings are required: text and background. Please.

**Comment by toolatetotheparty** [comment]
Please?

**Comment by metarmask** [comment]
I tried implementing this a while back but never managed to do it in a good way. I'll add an emergency CSS box tomorrow that'll allow you to do whatever you want.

**Comment by metarmask** [comment]
I have now added a box at the bottom of the options page.

To change the colors, input something like this:
```
body[class] {
    background: #ffffff;
    color: #000000;
}
```

**Comment by toolatetotheparty** [comment]
I have the april 7'th version, but don't see the box. Also, will the font-family work as well?

**Comment by toolatetotheparty** [comment]
Css settings won't save.

**Comment by metarmask** [comment]
What did you put in the box? Properties like `background` will be overriden by the theme so you'll need to increase specificity like in my example above. Also, make sure you press the check button next to the box.

**Comment by toolatetotheparty** [comment]
Ah yes, sorry. The moment I added the wildcard to body *, it worked. Thanks.

**Comment by marnovo** [comment]
My take on the custom CSS to be a bit more "refined" on macOS and akin to Safari Reader/Books (IMO the best implementation of all browsers):

```CSS
.sans-serif {
    font-family: "Source Sans Pro", sans-serif;
}

.serif {
    font-family: "Iowan Old Style", serif;
}

.monospace {
    font-family: "Source Code Pro", monospaced;
}

.light {
    color: #424242;
    background-color: #f0f0f0;
}

.dark {
    color: #dfdfdf;
    background-color: #5c5c60;
}

.sepia {
    color: #603e22;
    background-color: #faf4e8;
}
```

Additional question:

Is there somewhere you can access the current custom CSS you have active?
